### ISSUE TITLE
Cloning http mirrors doesn't seem to work

### ISSUE THREAD

**Issue by Leo675** [hackedteam/vector-ni#1]
Cloning the remote mirrors as instructed doesn't seem to work. I'm probably doing something wrong, but I tried every mirror and multiple repo dirs

It does seem like it might work if the .git dir is downloaded, then cloned locally though

**Comment by Polundra** [comment]
Perhaps you could provide torrent file also?

**Comment by hackedteam** [comment]
Cloning from HTTP mirrors should normally work, I tested it successfully earlier for another repo.
Some of the mirrors seem to be not responding or rejecting automated requests with a 503 so I updated the README with links to the torrent.

**Comment by wegwerfaccount** [comment]
Please try pushing to https://about.gitlab.com/gitlab-com/
